language: python
python:
  - "3.7.7"
services:
  - docker
before_install:
  - python --version
  - pip install -U pip
  - pip install docker-compose
  - pip install -U pytest
  - pip install codecov
  # - docker build -t thiagovf1988/docker_aws -f Dockerfile.dev .

cache: pip

install:
  - pip install -r requirements.txt
script:
  - python app.py